### ISSUE TITLE
Can not import from compiled DLL

### ISSUE THREAD

**Issue by htlcnn** [eirannejad/pyRevit#254] opened 2017-11-24 09:18 UTC
I have a python file with content:
```python
# D:\HTL\Desktop\test\htladdin.py
print("printed from inside dll")
```

I compiled it to `htladdin.dll` with this command:
```
"C:\Program Files (x86)\IronPython 2.7\ipy64.exe" "C:\Program Files (x86)\IronPython 2.7\Tools\Scripts\pyc.py" "D:\HTL\Desktop\test\htladdin.py" /out:htladdin
```

Then I add reference to it from my pyrevit script:
```python
# E:\Setup\UCE\Autodesk\Revit\pyRevit extensions\htl.extension\HTL.tab\Test.panel\Test.pushbutton\script.py
# -*- coding: utf-8 -*-

import clr
import sys

sys.path.append(r'D:\HTL\Desktop\test')
clr.AddReferenceToFile('htladdin.dll')

import htladdin
print(htladdin)
```

When I run the script inside Revit, Exception raised:
```
IronPython Traceback:
Traceback (most recent call last):
 File "E:\Setup\UCE\Autodesk\Revit\pyRevit extensions\htl.extension\HTL.tab\Test.panel\Test.pushbutton\script.py", line 9, in 
ImportError: No module named htladdin


Script Executor Traceback:
IronPython.Runtime.Exceptions.ImportException: No module named htladdin
 at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
 at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
 at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(String sourcePath, String syspaths, String cmdName, String cmdUniqueName, Boolean forcedDebugMode, Boolean altScriptMode, Dictionary`2& resultDict)
```

I was succeeded in adding reference and import the compiled DLL from ironpython console:
```
PS D:\HTL\Desktop\test> & 'C:\Program Files (x86)\IronPython 2.7\ipy64.exe'
IronPython 2.7.3 (2.7.0.40) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
>>> import sys
>>> sys.path.append(r'D:\HTL\Desktop\test')
>>> clr.AddReferenceToFile('htladdin.dll')
>>> import htladdin
printed from inside dll
>>> print(htladdin)
<module 'htladdin' from 'htladdin'>
>>>
```

**Comment by eirannejad** [comment] 2017-11-24 18:30
use `clr.AddReferenceToFileAndPath`

**Comment by htlcnn** [comment] 2017-11-25 01:31
@eirannejad still same Exception:
```python
# -*- coding: utf-8 -*-

import clr
import sys

clr.AddReferenceToFileAndPath(r'D:\HTL\Desktop\test\htladdin.dll')

import htladdin
print(htladdin)
```
```
IronPython Traceback:
Traceback (most recent call last):
 File "E:\Setup\UCE\Autodesk\Revit\pyRevit extensions\htl.extension\HTL.tab\Test.panel\Test.pushbutton\script.py", line 9, in 
ImportError: No module named htladdin


Script Executor Traceback:
IronPython.Runtime.Exceptions.ImportException: No module named htladdin
 at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
 at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
 at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(String sourcePath, String syspaths, String cmdName, String cmdUniqueName, Boolean forcedDebugMode, Boolean altScriptMode, Dictionary`2& resultDict)
```

**Comment by eirannejad** [comment] 2017-11-25 03:40
I believe in your IronPython tests you're importing the python file not the DLL file. You have the python file and the dll file in the same directory and add that to the sys.path

In your pyRevit script you're directly linking to the dll and it won't be able to import.

I tested my IronPython (same version as yours) and fails the import.

```
IronPython 2.7.3 (2.7.0.40) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
>>> clr.AddReferenceToFileAndPath(r'C:\Users\eirannejad\Desktop\htladdin.dll')
>>> import htladdin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named htladdin
>>>
```

```
IronPython 2.7.3 (2.7.0.40) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
>>> import sys
>>> sys.path.append(r'C:\Users\eirannejad\Desktop')
>>> clr.AddReference('htladdin')
>>> import htladdin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named htladdin
>>>
```

This is my script and the command to compile it:

``` python
def run(value):
    print("printed from inside dll {}".format(value))

```

```
"C:\Program Files (x86)\IronPython 2.7\ipy64.exe"\
"C:\Program Files (x86)\IronPython 2.7\Tools\Scripts\pyc.py"\
/main:"C:\Users\eirannejad\Desktop\htladdin.py"
/out:htladdin
/target:dll
/platform:x64
/embed
```
I'm closing this since this is not a pyRevit issue. Keep the conversation going please, I'd love to know the solution to this.

My hunch is that the compiled DLL does not have a namespace and it throws IronPython off. See the dotPeek view of the dll.

![2017-11-24 19_34_25-jetbrains dotpeek](https://user-images.githubusercontent.com/8197916/33226981-80dd331a-d14e-11e7-90fe-95439847ddb7.png)

If you try `import DLRCachedCode` it works since it's a type inside that dll.

I think you gotta find a way to compile the python into a dll that has a namespace other than the root namespace.

**Closed by eirannejad** 2017-11-25 03:40 UTC

**Comment by htlcnn** [comment] 2017-11-25 04:40
Actually I renamed `htladdin.py` to `htladdin1.py` before adding reference to the dll file. To clarify, I've now moved the python file to `\py` folder, then copied dll file outside to add reference.

This is my compile command:
```
"C:\Program Files (x86)\IronPython 2.7\ipy64.exe" "C:\Program Files (x86)\IronPython 2.7\Tools\Scripts\pyc.py" "D:\HTL\Desktop\test\py\htladdin.py" /target:dll /platform:x64 /embed
```
Note that I didn't add `/main` before file name because as I read in `pyc.py`: 
```
EXE/WinEXE specific options:
    /main:main_file.py                        Main file of the project (module to be executed first)
```

with that compile command, I was successful in adding reference to dll file, despite the content of the `htladdin.py` file:

```
Compiling message:
Input Files:
    D:\HTL\Desktop\test\py\htladdin.py
Output:
    htladdin
Target:
    Dll
Platform:
    ILOnly, PE32Plus
Machine:
    AMD64

Compiling...
Saved to htladdin
[Finished in 0.4s]
```

```
PS D:\HTL\Desktop\test> ls


    Directory: D:\HTL\Desktop\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       25/11/2017  11:28 AM                py
-a----       25/11/2017  11:39 AM           4608 htladdin.dll


PS D:\HTL\Desktop\test> & 'C:\Program Files (x86)\IronPython 2.7\ipy64.exe'
IronPython 2.7.3 (2.7.0.40) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
>>> clr.AddReferenceToFileAndPath(r'D:\HTL\Desktop\test\htladdin.dll')
>>> import htladdin
printed from inside dll
>>>
```

**Comment by htlcnn** [comment] 2017-12-05 16:00
@eirannejad 
Digging a little bit further, I noticed that I had successfully added reference to the dll file. This is my `script.py` code:
```python
# -*- coding: utf-8 -*-
import clr
import sys

clr.AddReferenceToFileAndPath(r'D:\HTL\Desktop\test\htladdin.dll')
print(clr.References)
```

and the output:
```
(<mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089>, 
<System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089>, 
<RevitAPI, Version=18.0.0.0, Culture=neutral, PublicKeyToken=null>, 
<RevitAPIUI, Version=18.0.0.0, Culture=neutral, PublicKeyToken=null>, 
<pyRevit_2018_a567b41e08226f67_PyRevitBaseClasses, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null>, 
<htladdin, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null>) 
```

**Comment by htlcnn** [comment] 2018-03-15 00:06
@eirannejad 
I've read and tried to use `clr.CompileModules` to make .dll file instead of using pyc.py. The compiled dll was successfully imported into ironpython interpreter (I renamed the original .py module to make sure it imports from dll file).
Here's the article's link: http://www.voidspace.org.uk/ironpython/dark-corners.shtml#static-compilation-of-python-code
But I still can't figure out why the same dll couldn't be imported into pyrevit scripts

**Comment by eirannejad** [comment] 2018-03-15 00:29
@htlcnn 
So apparently something has changed in IronPython 2.7.7 with these imports. I'll try to figure it out but if you go to pyRevit settings and activate the Dynamo Compatibility mode, save and reload Revit, it will load pyRevit using the 2.7.3 engine.

The dll imports work with the 2.7.3 engine which is the version of IronPython you have installed on your machine. I just tested this. Here are the 3 scripts:

Source module to be compiled: (file name `ehsantest.py`)
``` python
def somefunc(someval):
    print(someval)
somefunc(15)
```
Compiler script:
``` python
import sys
import os.path as op
thispath = op.dirname(__file__)
source = op.join(thispath, 'ehsantest.py')
dest = op.join(thispath, 'compiled', 'compiledehsantest.dll')
import clr
clr.CompileModules(dest, source)
```
``` bash
$ ipy64 compile.py
```

pyRevit script:
``` python
import clr
import sys

# add the path to the dll directory
sys.path.append(r"C:\Users\eirannejad\Desktop\compiled")
clr.AddReference("compiledehsantest")

# original python file name is the namespace
import ehsantest
```

As I mentioned, this however does not work with the 2.7.7 which is the default pyRevit engine. I'll look into it.

**Comment by eirannejad** [comment] 2018-03-15 00:39
Confirmed. Install IronPython 2.7.7 and compile using that. Then it perfectly loads in pyRevit. I'll do a blog post on this.

**Comment by htlcnn** [comment] 2019-11-04 12:09
@eirannejad sorry for digging this up.
I read about [Bundle Lib & bin](https://www.notion.so/Bundle-Lib-bin-f9c427c358ff4954bd671530973e3959), it says I can put some dll files in my extension's **bin** folder. For example: **htl.extension\bin\license.dll**. Then I can AddReference and import it for use in other child bundles.
Here's my child bundle's code:
```python
# -*- coding: utf-8 -*-
import clr
clr.AddReference('license.dll')
for r in clr.References:
    if str(r.GetName()).startswith('license'):
        print(r.CodeBase)

import license
```

Dll file is referenced successfully, but I can not import the namespace from it. Here is output:
```
file:///.../htl.extension/bin/license.DLL



IronPython Traceback:
Traceback (most recent call last):
 File "...\htl.extension\HTL.tab\Test.panel\views.stack\Test1.pushbutton\script.py", line 8, in <module>
ImportError: No module named license


Script Executor Traceback:
IronPython.Runtime.Exceptions.ImportException: No module named license
 at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
 at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```
Did I miss something?

**Comment by htlcnn** [comment] 2019-11-24 16:08
@eirannejad It's strange that although I compiled the dll using IronPython 2.7.7, I had to switch to IronPython 2.7.3 Engine in pyRevit settings in order to import and use the dll. Is there a mis-config here?

**Comment by eirannejad** [comment] 2019-11-24 17:05
Huh I don't think so. I have a [test tool for compiling and importing DLLs](https://github.com/eirannejad/pyRevit/tree/master/extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine%20Tests.pulldown/Test%20IronPython%20Compile.pushbutton) in the pyRevitDev extension and it passes the compile and import test under IronPython 2.7.7

**Comment by htlcnn** [comment] 2019-11-25 00:03
@eirannejad I ran your test on IronPython engine 2.7.3, it compiled and imported dll successfully. When I switched to IronPython engine 2.7.7, it compiled successfully but it imported .py file instead of .dll file.
I added a line to the code to show imported path:
```python
import ipycompiletest
print(ipycompiletest.__file__)
```


Output on IronPython engine 2.7.3:
```
﻿Compiled module level code works.
ipycompiletest
Compiled function works.
Compiled type works.
```


Output on IronPython engine 2.7.7:
```
﻿Compiled module level code works.
C:\pyRevit\dev\dev\extensions\pyRevitDevTools.extension\pyRevitDev.tab\Debug.panel\Engine Tests.pulldown\Test IronPython Compile.pushbutton\ipycompiletest.py
Compiled function works.
Compiled type works.
```
---
On 2.7.7, if I modified the code to rename .py file to other name, it failed to import.
```python
import sys
import os.path as op
import os
import clr

from pyrevit import USER_SYS_TEMP
from pyrevit import script
from pyrevit.framework import IO

# compile
try:
    source = script.get_bundle_file('ipycompiletest.py')
    dest = op.join(USER_SYS_TEMP, 'compiledipytest.dll')
    clr.CompileModules(dest, source)
    new_src = source.replace('ipycompiletest', 'ipycompiletest_old')
    os.rename(source, new_src)
except IO.IOException as ioerr:
    print('DLL file already exists...')
except Exception as cerr:
    print('Compilation failed: {}'.format(cerr))

# import test
sys.path.append(USER_SYS_TEMP)
clr.AddReferenceToFileAndPath(dest)

import ipycompiletest
print(ipycompiletest.__file__)
ipycompiletest.compile_test('Compiled function works.')

ipycompiletest.CompiledType('Compiled type works.')

```
Output:
```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\pyRevit\dev\dev\extensions\pyRevitDevTools.extension\pyRevitDev.tab\Debug.panel\Engine Tests.pulldown\Test IronPython Compile.pushbutton\script.py", line 26, in <module>
ImportError: No module named ipycompiletest


Script Executor Traceback:
IronPython.Runtime.Exceptions.ImportException: No module named ipycompiletest
 at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
 at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

By the way, is it comfortable to discuss on a closed issue? Should I open a new issue?

**Comment by digineer** [comment] 2019-11-25 11:39
By coincidence I was also testing how to compile iron python dlls and than calling them from pyrevit scripts this morning. At first I had the same issue: It worked when compiling with IronPython 2.7.3 and selecting pyRevit Engine 2.7.3 and then it did not work when compiling with IronPython 2.7.7 and pyRevit Engine 2.7.7. I don't know what I did but than suddenly it worked with IronPython 2.7.7 compilation and pyRevit Engine 2.7.7. Could this be a CACHE issue? Maybe deleting the files in C:\Users\YOURUSERNAME\AppData\Roaming\pyRevit\2019 will help. 

BTW: My end-goal is to use this workflow to create dlls from pyRevit scripts that can then be used with the Forge Revit Design Automation API which is now available to the public (see Autodesk Channel Newsletter from this morning). Writing pyRevit scripts and running them in the cloud. HOW COOL WOULD THAT BE!!!

**Comment by htlcnn** [comment] 2019-11-25 11:54
@digineer did you rename/move the source .py file to another path that it wouldn't be imported into your script.py? If you didn't, I'm afraid .py file was imported instead of compiled .dll file.

**Comment by digineer** [comment] 2019-11-25 12:22
@htlcnn Yes, I did. The source.py file lives on a completely different path and only the compiled dll is copied into the bundle from where it is loaded. To make extra sure I also deleted the original source.py and it still works.

**Comment by htlcnn** [comment] 2019-11-25 13:13
@digineer what's your `pyrevit env`? I couldn't get it imported on 2.7.7. I wonder if there was a change in import order from 2.7.3 to 2.7.7.

**Comment by digineer** [comment] 2019-11-25 13:19
I am running pyRevit 4.7.4 from the public installer.

**Comment by htlcnn** [comment] 2020-04-05 04:26
> Huh I don't think so. I have a [test tool for compiling and importing DLLs](https://github.com/eirannejad/pyRevit/tree/master/extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine%20Tests.pulldown/Test%20IronPython%20Compile.pushbutton) in the pyRevitDev extension and it passes the compile and import test under IronPython 2.7.7

@eirannejad I edited this button to print out `ipycompiletest`. It was actually the `ipycompiletest.py` file in the same bundle folder that got imported, not the compiled dll.

**Edited code:**
```python
import sys
import os.path as op
import clr

from pyrevit import USER_SYS_TEMP
from pyrevit import script
from pyrevit.framework import IO

# compile
try:
    source = script.get_bundle_file('ipycompiletest.py')
    dest = op.join(USER_SYS_TEMP, 'compiledipytest.dll')
    clr.CompileModules(dest, source)
except IO.IOException as ioerr:
    print('DLL file already exists...')
except Exception as cerr:
    print('Compilation failed: {}'.format(cerr))

# import test
sys.path.append(USER_SYS_TEMP)
clr.AddReferenceToFileAndPath(dest)

import ipycompiletest

print(ipycompiletest)

ipycompiletest.compile_test('Compiled function works.')

ipycompiletest.CompiledType('Compiled type works.')
```
**Output:**
```
Compiled module level code works.
<module 'ipycompiletest' from '...\Test IronPython Compile.pushbutton\ipycompiletest.py'>
Compiled function works.
Compiled type works.
```
I tried compiling and add reference to compiled dll outside of pyRevit, using `ipy.exe` that comes with IronPython installation. I also used `ipy` to import IronPython.Hosting.Python, CreateEngine and Execute a script. It was successful for both cases.

For pyRevit, I still don't understand what's the difference between a pyRevit engine and an ipy engine. Using `clr.AddReference(dll_file)` in pyRevit, dll file got added to `clr.References` but I couldn't import the namespace like I did with ipy console.

**Comment by htlcnn** [comment] 2020-04-05 13:40
@eirannejad Could you please explain the process of executing a button bundle? I tried to read your code but it seems to be quite complex for me because now pyRevit supports many different engines.
I tried created a C# addin that creates an IronPython engine and run a `.py` script to import a compiled dll. It was successful.
Most of the C# code to create IronPython engine was from pyRevit.
Please have a look: https://github.com/htlcnn/RevitIronPythonEngineTest
Many thanks!

**Comment by vasanth15** [comment] 2021-06-06 02:13
@htlcnn  I ran into the same issue, I am using ironPython 2.7.7, followed the same steps as mentioned above, successfully compiled the dlls, but hitting a road block here, for some reason, iron python can't find the module name. Were you able to import the dlls successfully? Thanks in advance.

![image](https://user-images.githubusercontent.com/15150829/120910231-06d1a880-c632-11eb-966f-90d74009497e.png)

**Comment by htlcnn** [comment] 2021-06-06 04:58
@vasanth15 Try 2.7.11 engine

**Comment by vasanth15** [comment] 2021-06-08 05:34
@htlcnn Yup, it works with 2710 version. Many thanks.!

With 2711, for some reason, on my pyrevit, it says it is a custom iron python engine (I hope, it is an interim version), it was able to identify the dll however, there were places where arguments mismatch occurred in pyrevit library. 

![image](https://user-images.githubusercontent.com/15150829/121128586-7be2e080-c7e0-11eb-9f1c-5512c8db9adb.png)
