### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Tomey77** [eirannejad/pyRevit#448] opened 2018-12-05 14:27 UTC
Hi I am getting a Unicode Decode Error when I click on any button on the pyRevit Tab.
Any help would be appreciated.

```
IronPythonTraceback:
Traceback (most recent call last):
File "C:\ADDONS\pyRevit\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\views.stack3\Views.pulldown\Open Referencing Sheet.pushbutton\script.py", line 3, in 
File "C:\ADDONS\pyRevit\pyrevitlib\pyrevit\revit\__init__.py", line 20, in 
File "C:\ADDONS\pyRevit\pyrevitlib\pyrevit\revit\ui.py", line 10, in 
File "C:\ADDONS\pyRevit\pyrevitlib\pyrevit\coreutils\loadertypes.py", line 5, in 
File "C:\ADDONS\pyRevit\pyrevitlib\pyrevit\loader\basetypes\__init__.py", line 198, in 
File "C:\ADDONS\pyRevit\pyrevitlib\pyrevit\coreutils\__init__.py", line 381, in find_loaded_asm
UnicodeDecodeError: ('unknown', u'\xfc', 0, 1, '')

Script Executor Traceback:
System.Text.DecoderFallbackException: Die Bytes [FC] im Index 0 k?nnen nicht von der angegebenen Codepage in Unicode ?bersetzt werden.
bei System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int32 index)
bei System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, Int32 index)
bei IronPython.Runtime.PythonAsciiEncoding.GetCharCount(Byte[] bytes, Int32 index, Int32 count)
bei System.Text.Encoding.GetChars(Byte[] bytes, Int32 index, Int32 count)
bei System.Text.Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
bei IronPython.Runtime.Operations.StringOps.RawDecode(CodeContext context, String s, Object encodingType, String errors)
bei IronPython.Runtime.Operations.StringOps.__new__(CodeContext context, PythonType cls, Object string, String encoding, String errors)
bei IronPython.Runtime.Operations.StringOps.CheckAsciiString(CodeContext context, String s)
bei CallSite.Target(Closure , CallSite , CodeContext , Object , Object )
bei IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
bei IronPython.Compiler.PythonCallTargets.OriginalCallTarget3(PythonFunction function, Object arg0, Object arg1, Object arg2)
bei System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
bei Microsoft.Scripting.Interpreter.FuncCallInstruction`6.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
bei IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
bei IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
bei IronPython.Runtime.PythonContext.InitializeModule(String fileName, ModuleContext moduleContext, ScriptCode scriptCode, ModuleOptions options)
bei IronPython.Runtime.Importer.LoadModuleFromSource(CodeContext context, String name, String path)
bei IronPython.Runtime.Importer.LoadFromDisk(CodeContext context, String name, String fullName, String str)
bei IronPython.Runtime.Importer.ImportFromPathHook(CodeContext context, String name, String fullName, List path, Func`5 defaultLoader)
bei IronPython.Runtime.Importer.ImportFromPath(CodeContext context, String name, String fullName, List path)
bei IronPython.Runtime.Importer.ImportNestedModule(CodeContext context, PythonModule module, String name, List path)
bei IronPython.Runtime.Importer.ImportModuleFrom(CodeContext context, Object from, String name)
bei IronPython.Runtime.Importer.ImportModule(CodeContext context, Object globals, String modName, Boolean bottom, Int32 level)
bei IronPython.Modules.Builtin.__import__(CodeContext context, String name, Object globals, Object locals, Object fromlist, Int32 level)
bei IronPython.Runtime.Importer.ImportLightThrow(CodeContext context, String fullName, PythonTuple from, Int32 level)
bei Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
bei IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
bei IronPython.Runtime.PythonContext.InitializeModule(String fileName, ModuleContext moduleContext, ScriptCode scriptCode, ModuleOptions options)
bei IronPython.Runtime.Importer.LoadModuleFromSource(CodeContext context, String name, String path)
bei IronPython.Runtime.Importer.LoadFromDisk(CodeContext context, String name, String fullName, String str)
bei IronPython.Runtime.Importer.ImportFromPathHook(CodeContext context, String name, String fullName, List path, Func`5 defaultLoader)
bei IronPython.Runtime.Importer.ImportFromPath(CodeContext context, String name, String fullName, List path)
bei IronPython.Runtime.Importer.ImportNestedModule(CodeContext context, PythonModule module, String name, List path)
bei IronPython.Runtime.Importer.ImportModuleFrom(CodeContext context, Object from, String name)
bei IronPython.Runtime.Importer.ImportModule(CodeContext context, Object globals, String modName, Boolean bottom, Int32 level)
bei IronPython.Modules.Builtin.__import__(CodeContext context, String name, Object globals, Object locals, Object fromlist, Int32 level)
bei IronPython.Runtime.Importer.ImportLightThrow(CodeContext context, String fullName, PythonTuple from, Int32 level)
bei Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
bei IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
bei IronPython.Runtime.PythonContext.InitializeModule(String fileName, ModuleContext moduleContext, ScriptCode scriptCode, ModuleOptions options)
bei IronPython.Runtime.Importer.LoadModuleFromSource(CodeContext context, String name, String path)
bei IronPython.Runtime.Importer.LoadFromDisk(CodeContext context, String name, String fullName, String str)
bei IronPython.Runtime.Importer.ImportFromPathHook(CodeContext context, String name, String fullName, List path, Func`5 defaultLoader)
bei IronPython.Runtime.Importer.ImportFromPath(CodeContext context, String name, String fullName, List path)
bei IronPython.Runtime.Importer.ImportNestedModule(CodeContext context, PythonModule module, String name, List path)
bei IronPython.Runtime.Importer.ImportModuleFrom(CodeContext context, Object from, String name)
bei IronPython.Runtime.Importer.ImportModule(CodeContext context, Object globals, String modName, Boolean bottom, Int32 level)
bei IronPython.Modules.Builtin.__import__(CodeContext context, String name, Object globals, Object locals, Object fromlist, Int32 level)
bei IronPython.Runtime.Importer.ImportLightThrow(CodeContext context, String fullName, PythonTuple from, Int32 level)
bei IronPython.Runtime.Operations.PythonOps.ImportStar(CodeContext context, String fullName, Int32 level)
bei Microsoft.Scripting.Interpreter.ActionCallInstruction`3.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
bei IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
bei IronPython.Runtime.PythonContext.InitializeModule(String fileName, ModuleContext moduleContext, ScriptCode scriptCode, ModuleOptions options)
bei IronPython.Runtime.Importer.LoadModuleFromSource(CodeContext context, String name, String path)
bei IronPython.Runtime.Importer.LoadFromDisk(CodeContext context, String name, String fullName, String str)
bei IronPython.Runtime.Importer.ImportFromPathHook(CodeContext context, String name, String fullName, List path, Func`5 defaultLoader)
bei IronPython.Runtime.Importer.ImportFromPath(CodeContext context, String name, String fullName, List path)
bei IronPython.Runtime.Importer.ImportNestedModule(CodeContext context, PythonModule module, String name, List path)
bei IronPython.Runtime.Importer.ImportFrom(CodeContext context, Object from, String name)
bei IronPython.Modules.Builtin.__import__(CodeContext context, String name, Object globals, Object locals, Object fromlist, Int32 level)
bei Microsoft.Scripting.Interpreter.FuncCallInstruction`7.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.LightLambda.Run7[T0,T1,T2,T3,T4,T5,T6,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
bei System.Dynamic.UpdateDelegates.UpdateAndExecute6[T0,T1,T2,T3,T4,T5,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
bei IronPython.Runtime.Importer.ImportLightThrow(CodeContext context, String fullName, PythonTuple from, Int32 level)
bei Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
bei Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
bei IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
bei PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)`
```

**Comment by eirannejad** [comment] 2018-12-06 17:25
Please share the script file. I have no idea what do you have in your script or what it is trying to do. There is a reason that the issue has a template with questions to be filled.

**Comment by Tomey77** [comment] 2018-12-06 20:00
I clicked the Open Referencing Sheet button. But it happens when I click
any button on the pyrevit tab. Even when I click reload or about.
Never had that issue before. Only happens since I've updated to v4.6.8

Am Do., 6. Dez. 2018, 18:25 hat Ehsan Iran-Nejad <notifications@github.com>
geschrieben:

**Comment by eirannejad** [comment] 2018-12-06 20:47
Okay. Got it. Would you please go to `%appdata%/pyRevit/<revit version>` and send me a screenshot of the files in that directory? Seems something about your user adds unicode characters to the DLL or module names. Do you have your extensions as well? Do they have unicode characters in the name?

**Comment by Tomey77** [comment] 2018-12-07 07:46
Files in `%appdata%/pyRevit/<revit version>`
pyRevit_2016_05948da64e59b102_pyRevitDevToolspyRevitDevDebugUnitTestsTestCSHARPScript.dll
pyRevit_2016_12504.log
pyRevit_2016_13976.log
pyRevit_2016_18420_runtime.log
pyRevit_2016_20419ed10287ca94_pyRevitDevTools.dll
pyRevit_2016_226f8872c2223f7e_pyRevitTutor.dll
pyRevit_2016_2276.log
pyRevit_2016_4964_runtime.log
pyRevit_2016_5612.log
pyRevit_2016_62843645fc03a81b_pyRevitTemplates.dll
pyRevit_2016_8208.log
pyRevit_2016_8b12d68d0e918e1b_pyRevitTags.dll
pyRevit_2016_9316.log
pyRevit_2016_9440.log
pyRevit_2016_b764f6787a9da0c8_PyRevitBaseClasses.dll
pyRevit_2016_cache_Cadimension.pickle
pyRevit_2016_cache_pyRevitCore.pickle
pyRevit_2016_cache_pyRevitDevTools.pickle
pyRevit_2016_cache_pyRevitTags.pickle
pyRevit_2016_cache_pyRevitTemplates.pickle
pyRevit_2016_cache_pyRevitTools.pickle
pyRevit_2016_cache_pyRevitTutor.pickle
pyRevit_2016_dafaf286b7f759cb_pyRevitCore.dll
pyRevit_2016_f740edf1f17c712c_pyRevitTools.dll

My Extension does not have any Unicode CHaracters in it but some of my buttons have. Is that a problem? Never was before the update.

Cheers

**Comment by eirannejad** [comment] 2018-12-07 16:50
My hunch is that there is another addin installed recently that has unicode names in the dll name. The `find_loaded_asm` listed in the error, is trying to find pyRevit's assembly in all loaded assemblies so it processes all the names.

Also pyRevit generates class names from the bundle names. Best practice is to name the bundle with simple non-unicode names and then set the `__title__` inside the script to the button title however you want.

**Comment by Tomey77** [comment] 2018-12-11 15:56
I removed all Unicode characters from the bundle names and now it is working.

The unicode characters were never a problem before. I still had them in there from before when c# scripts didn't have `__title__` 

Thanks for your help.

**Comment by eirannejad** [comment] 2018-12-11 18:08
This is very odd since I didn't change anything on the extension parser. No idea what's different. Would you be able to send me a few bundle names so I can replicate here and test?

**Comment by Tomey77** [comment] 2018-12-12 09:52
I have one bundle named:
Führungslinie mittig
that causes the error. As soon as I remove the "ü" it works fine.

**Comment by eirannejad** [comment] 2018-12-12 19:20
I tested it and it runs completely fine on mine on all revit versions. What IronPython engine are you using? 273 dynamo compatible?

**Comment by Tomey77** [comment] 2018-12-14 08:16
>What IronPython engine are you using? 273 dynamo compatible?

Aye

**Comment by eirannejad** [comment] 2018-12-14 17:18
Very interesting. It runs fine on both 277 and 273 engines on all my machines. Hmmm

**Comment by eirannejad** [comment] 2018-12-20 03:59
Closing this since the immediate issue has been resolved and the root cause can not be identified or the issue replicated.

**Closed by eirannejad** 2018-12-20 03:59 UTC
Labels: Heisenbug, Next Version
