### ISSUE TITLE
Error loading pyRevit on Revit 2023

### ISSUE THREAD

**Issue by paulollopes** [eirannejad/pyRevit#1510] opened 2022-04-08 09:12 UTC
Greetings

I've installed the pyRevit_4.8.10.22040_admin_signed.exe version and I'm having a problem loading pyRevit in Revit 2023. It works on Revit 2022, but not on the 2023.

See images below for error details

I have uninstalled all previous versions of it. Cleaned registry, Uninstalled Ironpython from my machine, nothing works. I would be happy to have a solution for it as pyRevit plays a huge role in our workflow.

Best regards

![01](https://user-images.githubusercontent.com/61492652/162404499-ecb6b5f0-e395-461c-8b38-62e2f30a9e0f.png)
![02](https://user-images.githubusercontent.com/61492652/162404534-0282ed8b-9727-4c21-8877-49bf1021f293.png)
.

**Comment by dagz214** [comment] 2022-04-08 11:23
I have issued a pull request that solves that ( #1508  ) you can take a look at the code until and if it will be merged.

**Comment by paulollopes** [comment] 2022-04-08 12:04
Thanks for the feedback @dagz214 

I'm afraid I'm a simple Revit user and I have no idea how to code. I would need some kind of "click and fix" solution :/

Shall I expect that sometime soon ?

Thanks again

**Comment by WesleyPipesIGOr** [comment] 2022-04-08 16:01
In the same boat as you. No coding experience here but it appears it is as simple as copying and pasting a few lines of text in a file to get it to work. I can confirm I have pyRevit working in Revit 2023 thanks to @dagz214!

The file you will want to modify is ScriptConsoleUtils.cs which can be found in your pyRevit install "C:\Users\USER\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\runtime". Open it up (I recommend Notepad++) and click the link @dagz214 shared, navigate to the Files Changed tab, then you will essentially be merging his code into the file. All the green highlighted lines are new and you can see how it shifts the numbers on the left (which Notepad++ should be showing). Copy paste, start Revit and it should all work! I recommend creating a backup of the file just in case too. Hope this helps and a big thanks to @dagz214 because I too so heavily rely on this addon!

**Comment by paulollopes** [comment] 2022-04-11 06:21
Followed the steps and I'm happy to anounce that it worked out perfectly. Thanks both @dagz214 for the solution and @WesleyPipesIGOr for the walkthrough!! 

Hope not so many people have this issue but If.. there is a solution for it.

Thanks a lot!!

**Closed** 2022-04-11 06:21 UTC

**Comment by Fozibehr** [comment] 2022-04-12 13:37
Excellent, thanks for the fix. All working again in my Revit 2023

**Comment by vosepherus** [comment] 2022-04-19 15:55
I've tried copying and pasting just the changes into the ScriptConsoleUtils.cs file and also deleting the entire contents of the file and copying and pasting from  @dagz214's post. I'm still getting the error message. I also tried restarting after updating the file and yes I'm saving over the old file. Nothing works. Can someone who has gotten it to work just post a copy of their ScriptConsoleUtils.cs file so I can just replace the existing with one that I know works? Thanks.

**Comment by Fozibehr** [comment] 2022-04-19 17:18
I just copied the whole file at https://github.com/eirannejad/pyRevit/pull/1508/files and everything was fine.
[ScriptConsoleUtils.zip](https://github.com/eirannejad/pyRevit/files/8515112/ScriptConsoleUtils.zip)

**Comment by vosepherus** [comment] 2022-04-19 17:26
I'm still getting the error message shown in the first post. Don't know what the problem could be, but thanks for uploading the file.

**Comment by Alakelele** [comment] 2022-06-14 04:21
Download the latest installers on this page, https://github.com/eirannejad/pyRevit/actions/runs/2158206100, congratulate the author at the same time.

Cheers

**Comment by GRArgo** [comment] 2023-12-20 23:09
Getting this same issue with the 4.8.12.23182 install for Revit 2023.  Help?
