### ISSUE TITLE
pyRevit Colour Coding addin for Architects

### ISSUE THREAD

**Issue by Robbo1234** [eirannejad/pyRevit#473] opened 2019-01-08 17:08 UTC
Would it be possible to create a colour coding addins for Architects similar to the Colour Coding addin in pyL_R?

![image](https://user-images.githubusercontent.com/8776947/50846731-c178f600-1367-11e9-80be-34bf1ecc701e.png)

**Comment by eirannejad** [comment] 2019-01-08 17:22
@Robbo1234 While I admire your enthusiasm and all the feature suggestions, I'd really appreciate if you follow the issue template format. The template text when you create an issue is there for a reason so I don't have to come back here and ask the same questions over and over.

Please respond to questions below:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by Robbo1234** [comment] 2019-01-16 09:44
**Is your feature request related to a problem? Please describe.**
Similar to the functionality of Color Splasher Revit Addin by BIM One which allows you to graphically visualise and verify the information in a model. It filters, selects and colours elements based on the values of a defined parameter to let you visualise if there are errors or a lack of information. 
User first selects the desired category, then selects a parameter and finally, sets colours for each value of this parameter.
This problem with this is that the BIM One Color Splasher doesn’t add a Color Fill Legend which hopefully pyRevit can resolve. :)

**Describe the solution you'd like**
A colour coding Revit Addin for Architects similar to the Colour Coding Addin in pyL_R than creates a Color Filled Legend.

In the meantime, I’ve been using this workaround to get Colour Fill Revit Legends to appear in a 3D View (Plan View).
![image](https://user-images.githubusercontent.com/8776947/51240103-f0e4bf80-1972-11e9-8b31-e93cb12efa34.png)

Note: An additional request is that maybe pyRevit could add this Revit Workaround as a PyRevit addin.

Describe alternatives you've considered
The BIM One Colour Splasher Addin: https://apps.autodesk.com/RVT/en/Detail/Index?id=5056644120649615847&appLang=en&os=Win64
 
**Additional context**
This screen shot shows a workflow for auditing Ceiling heights using the BIIM One Colour Splasher addin.

![image](https://user-images.githubusercontent.com/8776947/51240135-01953580-1973-11e9-8257-c5109c808255.png)

**Comment by deddolo** [comment] 2019-01-17 14:56
I was actually thinking about this the other day. I might give it a stab in the next few weeks if needed

**Comment by Robbo1234** [comment] 2019-01-17 16:31
Thanks Davide and Ehsan

**Comment by Robbo1234** [comment] 2021-02-01 22:31
I like the new Diroots OneFilter colour coding options.

Btw, @eirannejad do you when the next PyRevit release is out?

![image](https://user-images.githubusercontent.com/8776947/106525964-b9ef9100-64dc-11eb-8227-130eb7442e47.png)

**Comment by jmcouffin** [comment] 2022-12-25 19:30
> I like the new Diroots OneFilter colour coding options.

Considering this is a more than decent option, free, and we'll supported, I think we can close this issue.

**Closed by jmcouffin** 2022-12-25 19:30 UTC
Labels: Enhancement
