### ISSUE TITLE
Revit 2024 Crashes when loading but Revit 2022 doesnt

### ISSUE THREAD

**Issue by TMP361** [eirannejad/pyRevit#1866] opened 2023-07-10 14:28 UTC
**Describe the bug**

After installing the new version of pyRevit for Revit 2024, it just crashes without making it to the home page. I have followed all the steps in [pyRevit Is Installed But Does Not Load](https://pyrevitlabs.notion.site/pyRevit-Is-Installed-But-Does-Not-Load-f6495adb56254e9e8021f8a68e3b2ab7) and ran the `pyrevit attach master 277 --installed` command through command prompt. 

I have uninstalled and reinstalled Revit 2024 because I did try to use pyRevit while it was still a WIP for Revit 2024. I have also uninstalled and reinstalled pyRevit_4.8.13.23182_signed and pyRevit_4.8.13.23182_admin_signed multiple times. 

When I disable pyRevitLoader in the DIRoots App Manager Revit 2024 opens. I have both Revit 2024 and Revit 2022 installed. This version pyRevit works on Revit 2022 but not Revit 2024, so I don't think it's a SentileOne issue, but at the same time I am not a programer. 

**To Reproduce**
1. Install pyRevit
2. Open Revit
3. Crashes with no explaintation

**Expected behavior**
To open and use Revit

**Desktop (please complete the following information):**
 - OS: Wn64
 - pyRevit Version 4.8.13.23182
 - pyRevit Environment: Open a command prompt and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

 ```==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.13.23182+2215" | Path: "C:\Users\TMP361\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2024.0.1" | Engine: IPY277 (277) | Path: "C:\Users\TMP361\AppData\Roaming\pyRevit-Master"
master | Product: "2022 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Users\TMP361\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\TMP361\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2024.0.1 | Version: 24.0.5.432 | Build: 20230411_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: WMEISTER\TMP361
Active User: WMEISTER\TMP361
Admin Access: No
%APPDATA%: "C:\Users\TMP361\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.13.23182+2215
 ```
**Additional context**

**Comment by jmcouffin** [comment] 2023-07-10 17:33
> This version pyRevit works on Revit 2022 but not Revit 2024, so I don't think it's a SentileOne issue, but at the same time I am not a programer.

Do you have sentinel one setup on your network by your IT?
Revit 2024 must have been installed not so long ago, my guess is exclusions / exceptions setup in a firewall or security have not necessarily been arranged as well.

**Comment by TMP361** [comment] 2023-07-10 17:48
We do have Sentinel One setup. However, on Sentinel One it isn't triggering the crash according to our IT manager. Like nothing pops up on Sentinel One letting us know that it stopped Revit from crashing.

Wouldn't Sentinel One also stop Revit 2022 from opening as well with this version of pyRevit? Instead I am able to work on Revit 2022 with this version of pyRevit.

**Comment by jmcouffin** [comment] 2023-07-14 09:50
@TMP361 any news on your side?

**Comment by TMP361** [comment] 2023-07-14 13:03
I won't have an update until Monday

**Comment by jmcouffin** [comment] 2023-08-07 13:01
@Strider11 nothing extra from the #1751 
How did it go?

**Comment by jmcouffin** [comment] 2023-08-07 18:58
> I won't have an update until Monday

Any news? @TMP361

**Comment by Strider11** [comment] 2023-08-07 18:59
Finally got our IT service to add the exception to SentinelOne for pyRevit today.  It didn't seem to fix the issue.  Should I trying having github.com whitelisted as well?

**Comment by jmcouffin** [comment] 2023-08-07 19:10
I would monitor which folder do trigger S1 with you IT.

%appdata%/pyRevit and pyrevit-master folders for sure.

**Comment by Strider11** [comment] 2023-08-07 19:12
> I would monitor which folder do trigger S1 with you IT.
> 
> %appdata%/pyRevit and pyrevit-master folders for sure.

Okay, I'll try that. Thank you!  (Hopefully this time they respond faster than 3 weeks!)

**Comment by TMP361** [comment] 2023-08-08 11:32
I am in the process of convincing my IT that whitelisting these folders would hopefully fix the crashing. We had a data breach at the beginning of the year so we're still living with PTSD (rightfully so), thus trying to convince them to allow S1 to whitelist these folders raises red flags. 

I will keep you updated. Could there be something else or are we for sure it's S1?

**Comment by jmcouffin** [comment] 2023-08-08 11:38
@TMP361 
well, never 100% for sure. 
I don't have access to S1 neither.
S1 has been a fairly consistent source of issue to be able to work with pyRevit in the past 2 years or so.

**Comment by Strider11** [comment] 2023-08-08 21:24
@jmcouffin 
I was able to do a remote session with our IT and finally solve the issue.  It **was** S1 and the reason it wasn't fixed prior, was that my Revit is installed on the D: drive (for space reasons) rather than C:
Thank you so much for all your work on this plugin and help troubleshooting an issue that isn't with your software!!

**Comment by Strider11** [comment] 2023-08-10 02:48
> @Strider11 great For completeness, what did you have to whitelist in S1?

I don't know for sure, but my assumption is that it was: both C: drive& D: drive paths for Revit along with %appdata%/pyRevit and pyrevit-master folders are what ended up being whitelisted.

**Comment by jmcouffin** [comment] 2023-08-10 06:10
@TMP361 I will close the issue for now.

**Closed by jmcouffin** 2023-08-10 06:10 UTC
Labels: Not pyRevit Issue

**Comment by TMP361** [comment] 2023-08-21 13:36
@jmcouffin @Strider11 

So I finally got it to work. We excluded not the file path but the .exe for both Revit 2024 and pyRevit v4.8.13.23182. S1 was the problem everything works as intended.

**Comment by jmcouffin** [comment] 2023-08-21 14:37
@TMP361 Excellent, Thanks for the feedback. That will help others!

**Comment by jlow9** [comment] 2023-08-21 18:41
We have a similar situation to @TMP361.  We are running Revit 2024 and pyRevit v4.8.13.23182 and have SentinelOne in our environment.  We whitelisted:

C:\Program Files\Autodesk\Revit 2024\revit.exe
and
C:\Program Files\pyRevit-Master\bin\pyrevit.exe

from SentinelOne, and still are not able to launch.  Did you have any paths whitelisted previously?  Does anyone have a list of exclusions for Sentinel in order to launch Revit 2024 along with pyRevit?

**Comment by timwest95** [comment] 2023-11-15 18:29
> Does anyone have a list of exclusions for Sentinel in order to launch Revit 2024 along with pyRevit

I recently ran into this issue. I added the following exclusions in SentinelOne.

As file:
- C:\Program Files\Autodesk\Revit 2024\revit.exe
- C:\Users\*\AppData\Roaming\Autodesk\Revit\Addins\*\pyRevit.addin
- C:\ProgramData\Autodesk\Revit\Addins\*\pyRevit.addin

As folder:
- C:\Users\*\AppData\Roaming\pyRevit
- C:\Users\*\AppData\Roaming\pyRevit-Master
- C:\Program Files\pyRevit-Master

Exclusion settings in SentinelOne for all exclusions
- Exclusion Type: Path
- OS: Windows
- Include subfolders: checked
- Exclusions Mode: Interoperability

The end user confirmed pyRevit was working after adding the above exclusions.

**Comment by jmcouffin** [comment] 2023-11-15 18:54
Thanks for the update @timwest95 
This will definitely help others
