### ISSUE TITLE
Copying Shared and Project Parameters

### ISSUE THREAD

**Issue by Hazen12345** [eirannejad/pyRevit#531] opened 2019-02-26 18:46 UTC
Parameter manager to choose from lists within open Revit projects Categories listed.
To also add all of the parameters selected to merge with other families categories listed with the choice of checkboxes to select and unselect like filter tool.

Project or Shared parameters in families switch instance to type or vice versa.

Default Category with Default Name next to the parameters ID with the name the Author created. 

Hope that makes sense!

**Comment by eirannejad** [comment] 2019-02-26 20:03
Not really. I would have appreciated if you had followed the provided feature request format. This explanation doesn't give enough context so we understand what is your use case.

**Comment by Hazen12345** [comment] 2019-02-26 20:05
New tool!

Thx.

James

**Comment by eirannejad** [comment] 2019-02-26 20:06
Respond to questions below and be as specific as possible:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

Additional context Add any other context or screenshots about the feature request here.

**Comment by Hazen12345** [comment] 2019-02-26 20:07
Sorry thanks for updating to new Tool!

James

**Comment by Hazen12345** [comment] 2019-02-26 20:55
A Parameter Manager Interface, that reads and itemizes project and Shared parameters from a families already loaded in Models.
That also gives the user the ability to transfer replace or Substitute from family to family.
I
Check boxes or Some tools in the interface to change parameters from instance to type, and Create, Edit, Rename and Delete single or multiple parameters.

**Comment by CyrilWaechter** [comment] 2019-05-30 12:13
Duplicate of #335

**Comment by eirannejad** [comment] 2019-05-30 15:52
Closing this. Refer to #335 for updates

**Closed by eirannejad** 2019-05-30 15:52 UTC
Labels: New Tool
