### ISSUE TITLE
__revit__ is set to Application object instead of UIApplication object when creating a doc-opened.py script.

### ISSUE THREAD

**Issue by polmod** [eirannejad/pyRevit#1854] opened 2023-06-27 14:34 UTC
**Description**
I'm creating a hook using the doc-opened.py functionality.
I noticed that the variable `__revit__` is populated with an instance of the `Application `class. The documentation states that `__revit__ `should be populated with an instance of `UIApplication `class. 
Have I discovered a bug or is this behavior to be expected?

**To Reproduce**
1. Create a `doc-opened.py` script and look at the type of the `__revit__` variable.

**Expected behavior**
variable `__revit__` returns an instance of `UIApplication`.

**Screenshots**
![image](https://github.com/eirannejad/pyRevit/assets/82961917/9074582f-bffe-4fa7-8cfc-6a14be4e30b7)

**Desktop (please complete the following information):**
 - OS: Windows
 - pyRevit Version 4.8.12
 - pyRevit Environment: 

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\Paolo Modenese\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\Paolo Modenese\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\Paolo Modenese\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
011h | Type: Unknown | Repo: "" | Installed: "C:\Users\Paolo Modenese\Documents\pol\coding\local\construction.bim.011h_tab\src\011h.extension"
011h_COMPONENTS | Type: Unknown | Repo: "" | Installed: "C:\Users\Paolo Modenese\Documents\pol\coding\local\construction.bim.011h_tab\src\011h_COMPONENTS.extension"
011h_DEV | Type: Unknown | Repo: "" | Installed: "C:\Users\Paolo Modenese\Documents\pol\coding\tests\011h_DEV.extension"
==> Default Extension Search Path
C:\Users\Paolo Modenese\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\Paolo Modenese\Documents\pol\coding\tests
C:\Users\Paolo Modenese\Documents\pol\coding\local\construction.bim.011h_tab\src
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.11.19 | Build: 20220503_1030(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Comment by dosymep** [comment] 2023-06-28 12:11
i think it's because UIApplication doesn’t have this event

**Comment by polmod** [comment] 2023-06-28 14:04
Hi dosymep, but the __revit__ variable is something that is assigned by pyrevit... and at the moment the event is fired we already have available the document as `doc = EXEC_PARAMS.event_args.Document`
So then what I did is reassign the variable like so:
`uiapp = UI.UIApplication(__revit__)`
`__revit__ = uiapp`
I know the documentation discourages assigning a new value to this variable but I don't know what else to do honestly...

**Comment by jmcouffin** [comment] 2023-06-29 08:46
I guess we can close this issue @polmod unless you have a fix that can be implemented?

**Comment by polmod** [comment] 2023-06-29 09:02
Hi Jean-Marc!
No, I don't have a fix, but I haven't understood... is this behaviour to be
expected? or is it a bug? If it' sa bug I can try to find a fix for it.
Thank you

**Comment by jmcouffin** [comment] 2023-06-29 09:42
IMHO It is an expected behaviour.

**Comment by jmcouffin** [comment] 2023-06-29 09:43
I will close the issue. Let me know if it needs reopening

**Closed by jmcouffin** 2023-06-29 09:43 UTC
Labels: Extension Hooks
