### ISSUE TITLE
[Bug]: develop-4 branch only IOError: System.IO.IOException: Could not add reference to assembly pyRevitLabs.Emojis

### ISSUE THREAD

**Issue by acco-jpitts** [eirannejad/pyRevit#2173] opened 2024-03-27 15:21 UTC
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Switching from pyRevit Master branch to develop-4 causes pyRevit to fail to load for Revit 2020-2024.
![image](https://github.com/eirannejad/pyRevit/assets/104219512/d2fd047d-a58c-4f88-b1c4-8e0590d0f041)

### ⌨ Error/Debug Message

```shell
IOError: System.IO.IOException: Could not add reference to assembly pyRevitLabs.Emojis
```

### ♻️ To Reproduce

1. Install pyrevit using our standard installation script, but specify the develop-4 branch instead of master
OR
Switch branches using Github Desktop

2. Open Revit and get error that "Could not add reference to assembly pyRevitLabs.Emojis"

### ⏲️ Expected behavior

Expect to be able to start Revit with the develop-4 btanch of pyRevit.

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
pyRevit | Branch: "develop-4" | Version: "4.8.15:f079f5f" | Path: "C:\pyRevit-Master\pyRevit"
==> Registered Clones (deployed from archive/image)
==> Attachments
pyRevit | Product: "24.2" | Engine: DEFAULT (2711) | Path: "C:\pyRevit-Master\pyRevit" | AllUsers
pyRevit | Product: "23.1.3" | Engine: DEFAULT (2711) | Path: "C:\pyRevit-Master\pyRevit" | AllUsers
pyRevit | Product: "2022.1.5" | Engine: DEFAULT (2711) | Path: "C:\pyRevit-Master\pyRevit" | AllUsers
pyRevit | Product: "2021.1.9" | Engine: DEFAULT (2711) | Path: "C:\pyRevit-Master\pyRevit" | AllUsers
pyRevit | Product: "2020.2.9" | Engine: DEFAULT (2711) | Path: "C:\pyRevit-Master\pyRevit" | AllUsers
==> Installed Extensions
ACCO_VC | Type: UIExtension | Repo: "https://github.com/our_ribbon.git" | Installed: "C:\pyRevit-Master\extensions\ACCO_VC.extension"
==> Default Extension Search Path
C:\Users\username\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\pyRevit-Master\extensions
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.9 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.9 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
PID: 27304 | 24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: username
Active User: username
Admin Access: No
%APPDATA%: "C:\Users\jpitts\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7 v4.7.2 v4.8 v4.8.1 v4.X
Installed .Net-Core Target Packs: v2.1.202 v6.0.420 v8.0.202
pyRevit CLI v4.8.15.24085+1553-wip.f079f5fd51756b988a06d005d4f4cd2961f36e63
```

```
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
dev | Deploy: "" | Branch: "develop-4" | Version: "4.8.15" | Path: "C:\pyRevit-Master\dev"
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.14.24016+1909" | Path: "C:\pyRevit-Master\master"
==> Attachments
dev | Product: "24.2" | Engine: DEFAULT (2711) | Path: "C:\pyRevit-Master\dev" | AllUsers
dev | Product: "23.1.3" | Engine: DEFAULT (2711) | Path: "C:\pyRevit-Master\dev" | AllUsers
dev | Product: "2022.1.5" | Engine: DEFAULT (2711) | Path: "C:\pyRevit-Master\dev" | AllUsers
dev | Product: "2021.1.9" | Engine: DEFAULT (2711) | Path: "C:\pyRevit-Master\dev" | AllUsers
dev | Product: "2020.2.9" | Engine: DEFAULT (2711) | Path: "C:\pyRevit-Master\dev" | AllUsers
==> Installed Extensions
ACCO_VC | Type: UIExtension | Repo: "https://github.com/our_ribbon.git" | Installed: "C:\pyRevit-Master\extensions\ACCO_VC.extension"
==> Default Extension Search Path
C:\Users\username\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\pyRevit-Master\extensions
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.9 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.9 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
PID: 2732 | 24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: username
Active User: username
Admin Access: No
%APPDATA%: "C:\Users\username\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7 v4.7.2 v4.8 v4.8.1 v4.X
Installed .Net-Core Target Packs: v2.1.202 v6.0.420 v8.0.202
pyRevit CLI v4.8.15.24085+1553-wip.f079f5fd51756b988a06d005d4f4cd2961f36e63
```
```


### Additional context

I tried with multiple installation configurations as shown in the 2 different pyrevit env outputs shown below. The is no issue using the master branch. It is only the develop-4 branch with the load failure.

I performed all of the trouble shooting steps, including moving all of the addin folders and rebooting, as well as removal of all pyrevit files in all locations before attempting to install.

**Comment by sanzoghenzo** [comment] 2024-03-27 18:43
Hi @acco-jpitts,
We introduced some changes and removed most of the dlls from the repository; I don't think it will be possible to switch branches anymore.
If you want to check new features or fixed done in the develop-4 branch, you're better off downloading and installing the WIP installers you can find in the actions section, such as [this one](https://github.com/eirannejad/pyRevit/actions/runs/8422954878)

**Comment by acco-jpitts** [comment] 2024-03-27 19:07
> Hi @acco-jpitts, We introduced some changes and removed most of the dlls from the repository; I don't think it will be possible to switch branches anymore. If you want to check new features or fixed done in the develop-4 branch, you're better off downloading and installing the WIP installers you can find in the actions section, such as [this one](https://github.com/eirannejad/pyRevit/actions/runs/8422954878)

pretty sure that is same WIP version installer I'm using. 

![image](https://github.com/eirannejad/pyRevit/assets/104219512/6c501d6f-75e9-4720-bcae-174b14e67bda)

**Comment by sanzoghenzo** [comment] 2024-03-27 19:42
I may be wrong, but if you install the wip version the pyrevit-Master folder is already a snapshot of the develop-4 branch, with the added bonus that the dlls are compiled and shipped inside that folder.

@eirannejad have we broken the clones management by removing the dlls from the repository? Should we rethink the whole clones behavior?

**Comment by jmcouffin** [comment] 2024-03-28 08:07
I haven't had any issue myself foing exactly that: 
- WIP installer,
- then switching between dev-4 and dev-4 cloned branches.

**Comment by sanzoghenzo** [comment] 2024-03-28 08:23
Sorry, I should shut up and let the grown up talking, I don't even know how to switch clones 😅 - I will try to do it and see if I can reproduce.

In the meantime, just to be sure:

> 1. Install pyrevit using our standard installation script, but specify the develop-4 branch instead of master

What is your "standard installation script"? what does it do?

**Comment by acco-jpitts** [comment] 2024-03-28 17:05
try the following installation script to reproduce the issue. Place both the bat file and the ps1 script file in the same folder as the pyRevit_CLI_4.8.15.24085_admin_signed.exe from the latest WIP release.

Also added the installation command for ndp48-devpak if its needed but commented out since I'm assuming you have this...

when "$condition = $True" at the top of the powershell script, pyrevit should load without issue.
when "$condition = $False" at the top of the powershell script, pyrevit will not load due to the dll's missing.

I'm assuming when you say "installer" you mean the non-CLI installer. This would not be ideal if future deployments could not be done using cloned repo.

Check the paths I'm using, as script will make sure these paths are clean before cloning pyrevit to it.

This is pretty close to my standard installation script, but with the toggle for testing the dev vs master added, and removal of my extension install since it is a private repo and not relevant to the issue anyways.

simplified-installer.bat
```
@ECHO OFF
@setlocal enableextensions
@cd /d "%~dp0"
set "scriptPath=%~dp0"
REM  --> Check for permissions
"%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system">nul 2>NUL

REM --> If error flag set, we do not have admin.
if '%errorlevel%' NEQ '0' (
    echo Requesting administrative privileges...
    goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
    if exist "%temp%\getadmin.vbs" (
        del "%temp%\getadmin.vbs"
        echo Failed to acquire elevated privilege.  Try saving this script and running it from your Desktop.
        echo;
        echo Press any key to exit.
        pause>NUL
        goto :EOF
    )
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    echo UAC.ShellExecute "%~s0", "%*", "", "runas", 1 >> "%temp%\getadmin.vbs"

    cscript /nologo "%temp%\getadmin.vbs"
    goto :EOF

:gotAdmin
    if exist "%temp%\getadmin.vbs" ( del "%temp%\getadmin.vbs" )
:--------------------------------------
cls

powershell.exe -executionpolicy bypass -Command "& '%scriptPath%\simplified-installer.ps1'"
pause
```


simplified-installer.ps1
```
If ($env:PROCESSOR_ARCHITEW6432 -eq "AMD64") {
    Try {
        & "$ENV:WINDIR\SysNative\WindowsPowershell\v1.0\PowerShell.exe" -NonInteractive -NoProfile -File $PSCOMMANDPATH
    }
    Catch {
        Throw "Failed to start $PSCOMMANDPATH"
    }
    Exit
}


##########################Set to True for "master" or False for "develop-4"###################
$condition = $True
##############################################################################################







if ($condition) {
    $ourclonename = "pyRevit"
    $pyrevitbranch = "master"
} else {
    $ourclonename = "pyRevit-dev4"
    $pyrevitbranch = "develop-4"
}

$env:Path = "C:\Program Files\pyRevit CLI\bin"
$pyrevitinstaller = $PSScriptRoot
$pyrevitroot = "C:\pyRevit-Master"
$pyrevitclone = "$($pyrevitroot)\$($ourclonename)"






# install CLI dependencies - Assuming you already have this installed
# Write-Output "Installing .Net (4.8)..."
# Start-Process -FilePath "$($pyrevitinstaller)\ndp48-devpack-enu.exe" `
              # -ArgumentList "/q /norestart" `
              # -Wait `
              # -Verb RunAs > $null

# install/update pyRevit CLI - place in same folder as this powershell script
Write-Output "Installing pyRevitCLI 4.8.15..."
Start-Process -FilePath "$($pyrevitinstaller)\pyRevit_CLI_4.8.15.24085_admin_signed.exe" `
              -Wait `
              -ArgumentList "/VERYSILENT /NORESTART" > $null
		  
function Remove-Path ([string] $targetpath) {
    Write-Output "Confirming $($targetpath)"
    If (Test-Path $targetpath) {
        Remove-Item -Path $targetpath -Recurse -Force
    }
}

function Remove-Previous-Versions {
	Remove-Path $pyrevitclone
}

# clone pyRevit
function Clone-PyRevit() {
    # close all open Revits first
    Write-Output "Closing All Revits..."
    pyrevit revits killall
    # forget all previous pyRevit clones if any
    pyrevit clones forget $ourclonename > $null
    # clone pyRevit now
    Write-Output "Cloning pyRevit master..."
	Write-Host "Clone Name: $ourclonename"
	Write-Host "Branch: $pyrevitbranch"
    pyrevit clone $ourclonename --branch=$pyrevitbranch --dest=$pyrevitroot --debug
}
	
function Configure-PyRevit() {
    Write-Output "Configuring pyRevit..."
    pyrevit configs logs none
    pyrevit configs checkupdates enable
    pyrevit configs autoupdate enable
    pyrevit configs rocketmode enable
    pyrevit configs filelogging disable
    pyrevit configs loadbeta disable

    # this final step is critical
    # this seeds the config file for all the future users
		pyrevit configs seed --debug
}

function Attach-PyRevit() {
    Write-Output "Attaching pyRevit to Installed Revits..."
    pyrevit attach $ourclonename default --installed --debug  
}

function Test-CommandExists {
    param ($command)
    $oldPreference = $ErrorActionPreference
    $ErrorActionPreference = 'stop'
    try {
        if(Get-Command $command){
            return $true
        }
    }
    catch {
        return $false
    }
    finally {
        $ErrorActionPreference=$oldPreference
    }
}

if (Test-CommandExists "pyrevit") {
		Remove-Previous-Versions
		Clone-PyRevit --debug
		Configure-PyRevit --debug
    Attach-PyRevit --debug
}
```

**Comment by acco-jpitts** [comment] 2024-03-28 17:24
Well looks like copying over the bin folder created by the non-CLI installer and adding to the clone bin folder allows pyrevit to load the ribbon successfully. Is there anyway to handle this other than zipping these dlls myself and expanding into the bin folder manually after cloning?

I see now that it is recommended to use a deployment instead of a clone of the whole branch. I have been using the cloned master branch for pyrevit, so maybe I need to reconsider this approach. 

Would the deployments include these missing bin files once develop-4 is merged back to master? They are not included when using  develop-4 deployments currently.

**Comment by jmcouffin** [comment] 2024-03-29 09:07
> Would the deployments include these missing bin files once develop-4 is merged back to master? They are not included when using develop-4 deployments currently.

yes, they will
but I still need to press the release button to make sure the CI works accordingly.

> Well looks like copying over the bin folder created by the non-CLI installer and adding to the clone bin folder allows pyrevit to load the ribbon successfully. Is there anyway to handle this other than zipping these dlls myself and expanding into the bin folder manually after cloning?

you are right.

> Sorry, I should shut up and let the grown up talking, I don't even know how to switch clones 😅 - I will try to do it and see if I can reproduce.

I plan on graduating to grown up in the coming years / decades. ;p 

@sanzoghenzo we may have broken a workflow on the dev side removing the dlls ;p

**Comment by sanzoghenzo** [comment] 2024-03-29 09:56
> > Would the deployments include these missing bin files once develop-4 is merged back to master? They are not included when using develop-4 deployments currently.
> 
> yes, they will but I still need to press the release button to make sure the CI works accordingly.

I don't think this will be the case anymore, since if you merge develop-4 to master, there will be no more dlls in the bin directory.

Since this is a breaking change, I suppose that we should revert back to having the dlls into the repository and only remove them on the develop branch - and we should discuss about the future of the pyrevit cli at the next online meeting!

> Well looks like copying over the bin folder created by the non-CLI installer and adding to the clone bin folder allows pyrevit to load the ribbon successfully.

The files are also in the CLI folder (I don' have admin rights, so for me is `%localappdata%\pyrevit cli`), so the CLI could take care of copying over the bin files after the clone. Not sure if there's some missing file to take care for.

**Comment by jmcouffin** [comment] 2024-03-29 10:17
> Since this is a breaking change, I suppose that we should revert back to having the dlls into the repository and only remove them on the develop branch - and we should discuss about the future of the pyrevit cli at the next online meeting!

bringing back the dlls into the master right now 😨 😄 👿 
@sanzoghenzo

**Comment by sanzoghenzo** [comment] 2024-03-29 10:21
great, I just sent you a DM on discourse, let me know if you need help

**Comment by acco-jpitts** [comment] 2024-03-29 18:19
Thank you for your attention on this guys. I ended up just forking and committing those bins myself just to get up and running for testing.

Is there previous public discussion somewhere you can point me to for the reasoning behind removing these dlls or is it easy explanation? I'm assuming it has something to do with needing to build against both net48 and net80?

**Comment by sanzoghenzo** [comment] 2024-03-29 20:26
> Is there previous public discussion somewhere you can point me to for the reasoning behind removing these dlls or is it easy explanation? I'm assuming it has something to do with needing to build against both net48 and net80?

There was a brief private discussion, but definitely not much thinking through it!
I myself was a promoter of removing binary files from the git repo, because it's not what a git repo is made for, but it didn't occur to me that clones and deployments use git content to work properly. (I only use the default, non-cli installer, so I had no direct experience with the cli)

**Comment by jmcouffin** [comment] 2024-03-30 13:38
I will close it. Thanks for the heads-up @acco-jpitts 
Everything is back to 'normal'
The CLI or pyRevit, installed from the latest wip installers should behave normally .
Switching between branches from the CLI as Well

**Closed by jmcouffin** 2024-03-30 13:38 UTC
Labels: Bug, Prioritize, Command Line Utility (CLI), CI/CD
