### ISSUE TITLE
Telemetry not writing host_user randomly

### ISSUE THREAD

**Issue by Dre-Tas** [eirannejad/pyRevit#1225] opened 2021-04-21 01:23 UTC
We're using the Telemetry system to track the usage of pyRevit and our own toolbar hosted on pyRevit.

I've just noticed an odd behaviour happening with **just one user** that sometimes fails to have the _host_user_ field populated:

I'm also failing at recognising a pattern in this so really not sure what's going on.

Did this happen before with someone else?

Cheers

**Comment by eirannejad** [comment] 2021-04-21 17:48
`host_user` is the currently logged-in user on that machine. Seems like the [code here](https://github.com/eirannejad/pyRevit/blob/7eb0a4e1f6d2509735b2da80168b1c8b0e5b2f20/dev/pyRevitLabs/pyRevitLabs.Common/UserEnv.cs#L77) returns NULL sometimes.

**Comment by Dre-Tas** [comment] 2021-04-22 23:38
Thanks Ehsan!
Is that commit fixing it in the next release?

**Comment by eirannejad** [comment] 2021-04-23 04:57
Hopefully but I'm not sure I have actually found the root cause.

**Comment by Dre-Tas** [comment] 2021-04-23 05:39
Would it help if we tested it?

**Comment by eirannejad** [comment] 2021-05-17 03:12
v4.8.8 released with the attempted fix :D Hope this resolved the issue.

https://github.com/eirannejad/pyRevit/releases/tag/v4.8.8

**Comment by Dre-Tas** [comment] 2021-05-24 04:24
It happened again. I'm afraid 4.8.8 didn't fix it 😢

**Comment by Dre-Tas** [comment] 2021-05-27 03:06
@eirannejad we told our users to update their version of pyRevit to 4.8.8 in order to fix this issue, but it looks like the issue is still occurring from time to time.
So I was wondering: is it just a matter of updating pyRevit or do we have to do some work/updates on the server too?

**Comment by eirannejad** [comment] 2021-12-29 21:26
Moved to https://github.com/eirannejad/pyRevit/issues/1434

**Closed** 2021-12-29 21:25 UTC
Labels: Telemetry
